// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksUNfA2MYlYxIRH4cb0n46iRKR7tNy-g',
    appId: '1:794177788707:web:bce2e7c8c675c147a9ca96',
    messagingSenderId: '794177788707',
    projectId: 'sharvari-b960d',
    authDomain: 'sharvari-b960d.firebaseapp.com',
    storageBucket: 'sharvari-b960d.firebasestorage.app',
    measurementId: 'G-TCH1VM0PM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqZnzeNISPh2mIjoS97kr6U8mDV1A5rV0',
    appId: '1:794177788707:android:44bc73d7e4ee6002a9ca96',
    messagingSenderId: '794177788707',
    projectId: 'sharvari-b960d',
    storageBucket: 'sharvari-b960d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W_Fjt8ZVN2y83DOu9SgnFXPdbLnDf-w',
    appId: '1:794177788707:ios:4027eff0a354c31da9ca96',
    messagingSenderId: '794177788707',
    projectId: 'sharvari-b960d',
    storageBucket: 'sharvari-b960d.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W_Fjt8ZVN2y83DOu9SgnFXPdbLnDf-w',
    appId: '1:794177788707:ios:4027eff0a354c31da9ca96',
    messagingSenderId: '794177788707',
    projectId: 'sharvari-b960d',
    storageBucket: 'sharvari-b960d.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksUNfA2MYlYxIRH4cb0n46iRKR7tNy-g',
    appId: '1:794177788707:web:2b02a1927456b695a9ca96',
    messagingSenderId: '794177788707',
    projectId: 'sharvari-b960d',
    authDomain: 'sharvari-b960d.firebaseapp.com',
    storageBucket: 'sharvari-b960d.firebasestorage.app',
    measurementId: 'G-MKG6BK65QQ',
  );
}
